### ISSUE TITLE
Recursive function call

### ISSUE THREAD

**Issue by pixelgrid** [TehShrike/just-flatten#1]
You are making a recursive function call for everything even if its not a nested array.
Can make the code cleaner yes but for large arrays this could be a performance issue

**Comment by TehShrike** [comment]
I actually doubt that this would be a performance issue.  Modern JavaScript engines have optimized the function call to a crazy degree, and considering that the function in question (`flatten`) looks like a prime candidate for V8's optimizing compiler, I'd have to see some realistic-looking benchmarks to be convinced that the less-simple version would be faster.

Beyond that, I do quite value simplicity.  It's why I prefer higher-order functions like `reduce` to `for`-loops.

I'll close this for now, but if anyone feels like taking a stab at some benchmarking, I'd be interested to see it!

**Comment by pixelgrid** [comment]
This is how lodash and underscore handle flattening of arrays
 [Lodash](https://github.com/lodash/lodash/blob/master/dist/lodash.js#L2687)  
[Underscore](https://github.com/jashkenas/underscore/blob/master/underscore.js#L504)  

I guess benchmarks were done for them.

Also this would also be a simple but bad performance solution

`module.exports = x => JSON.parse('[' + x + ']')`

**Comment by TehShrike** [comment]
If there's a benchmark suite around for Lodash/Underscore, it would be cool to get it to run this flatten function as a comparison!

Note that this module literally just flattens arrays, and doesn't take any of those other arguments that the Lodash/Underscore versions do.

That JSON.parse implementation doesn't work to flatten input arrays, but setting that aside, I don't think that implementation is simpler.  It is less lines, but it involves type coercion of the input type to string, and then doing something clever to try to twist it into the desired output form.

I believe that type-respecting code that describes what is being done as accurately as possible, while mutating as little state as possible, is the path to simplicity.

And when it comes down to it, I value simplicity over performance (though as I said, I doubt that this implementation would actually be appreciably slower than those others in a modern JS engine).

I would highly recommend watching Rich Hickey's talk "[Simple Made Easy](https://www.infoq.com/presentations/Simple-Made-Easy-QCon-London-2012)", it is fantastic.
